name: Auto merge pull requests

on:
  pull_request_review:
    types:
      - submitted

  check_suite:
    types:
      - completed

  status: {}

jobs:
  autosquash-renovate:

    name: Auto squash (Renovate)
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.repo.full_name == 'ybw0014/guizhan-builds'

    steps:
    - name: Auto squash
      uses: pascalgn/automerge-action@v0.15.3
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        UPDATE_RETRIES: 0
        MERGE_METHOD: squash
        MERGE_FORKS: false
        MERGE_DELETE_BRANCH: true
        MERGE_LABELS: 'dependency'
        MERGE_COMMIT_MESSAGE: '[CI skip] ${{ github.event.pull_request.title }}'
