name: Auto approve

on: pull_request

jobs:
  auto-approve:
    name: Auto approve Pull Request
    runs-on: ubuntu-latest

    # for hmarr/auto-approve-action to approve PRs
    permissions:
      pull-requests: write

    if: github.event.pull_request.head.repo.full_name == 'ybw0014/guizhan-builds'

    steps:
    - name: Approve via actions
      uses: hmarr/auto-approve-action@v2.4.0
      if: github.actor == 'GuizhanBot' || github.actor == 'renovate[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
